const AUTHENTICATION_ERROR = 1000;
const READ_DOCUMENT_ERROR = 1001;
const ADD_DOCUMENT_ERROR = 1002;
const UPDATE_DOCUMENT_ERROR = 1003;
const DELETE_DOCUMENT_ERROR = 1004;
const CHANGE_SHOWARR_ERROR = 1005;
const INVALID_ARGUMENTS = 1006;

const AUTHENTICATION_SUCCESS = 2000;
const ADD_DOCUMENT_SUCCESS = 2002;
const UPDATE_DOCUMENT_SUCCESS = 2003;
const DELETE_DOCUMENT_SUCCESS = 2004;
const CHANGE_SHOWARR_SUCCESS = 2005;

export {
  AUTHENTICATION_SUCCESS,
  AUTHENTICATION_ERROR,
  READ_DOCUMENT_ERROR,
  ADD_DOCUMENT_SUCCESS,
  ADD_DOCUMENT_ERROR,
  UPDATE_DOCUMENT_SUCCESS,
  UPDATE_DOCUMENT_ERROR,
  DELETE_DOCUMENT_SUCCESS,
  DELETE_DOCUMENT_ERROR,
  CHANGE_SHOWARR_SUCCESS,
  CHANGE_SHOWARR_ERROR,
  INVALID_ARGUMENTS
};
